# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('number_of_cases', models.IntegerField()),
                ('population', models.IntegerField()),
                ('rate', models.FloatField()),
                ('CI_lower', models.FloatField()),
                ('CI_upper', models.FloatField()),
            ],
        ),
    ]
